### ISSUE TITLE
nov commite

### ISSUE THREAD

**Issue by TejaR** [TejaR/APPR-2014-15#6]
Malo sem posodila svoj projekt. Prmosil, da mi ga posodobite na zadnji commite in sicer:
TejaR/APPR-2014-15@2f2a4355ddb18e96fe91d806dec640fe269d6358
 Hvala!

**Comment by jaanos** [comment]
To je sicer mišljeno, da gre na repozitorij s povezavami na vaše projekte. Sem posodobil, tako da lahko zapreš.

**Comment by TejaR** [comment]
Hvala!

Teja Rupnik
